### PR TITLE
add some style to the app and also add fevicon

### PR DESCRIPTION
**Pull request by akshayvinchurkar**
add some style to the app and also add favicon its not upto the mark style but i spend some time so

### CODE REVIEW

**Review by SondaSengupta — APPROVED** [review]
Looks really amazing.

**Comment by SondaSengupta** [comment]
:+1:

**Comment by akshayvinchurkar** [comment]
Thanks looking for more contribution :simple_smile:

**Comment by akshayvinchurkar** [comment]
thanks :sparkles:

**Pull request merged**
